# Generated by Django 3.1 on 2022-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
    ]
